audit_header: false
title: Houston Real Estate Video Blog with The Franklin Team
description: Our mission at eXp Realty is to be your best resource for Houston real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The eXp Realty, your professional Houston Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:

client:
  name: The Franklin Team
  title:
  license_number:
  about_markdown: |
    It is the mission of The Franklin Team to exceed your expectations in buying or selling your home and to make your experience a positive one. Our main objective is to efficiently deliver world class service with accuracy, integrity and professionalism. Our goal is to create clients for life with an experience that's worthy of your personal referrals!
  brand: eXp Realty
  brokerage:
  market: Houston
  address: 23302 W Fernhurst Dr, Ste 100, Katy, TX 77494
  phone: 281-347-2200
  phone_type:
  phone2:
  phone2_type:
  email: team@thefranklinteaminc.com
  url: http://www.thefranklinteaminc.com

CTAs:
  first_CTA_text: Why HBP?
  first_CTA_URL: https://www.hbprogram.com/why-hbp
  second_CTA_text: Lease Buyout Application
  second_CTA_URL: https://www.hbprogram.com/copy-of-getting-started
  third_CTA_text: Home Buyout Application
  third_CTA_URL: https://www.hbprogram.com/copy-of-lease-buyout-app

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "Why HBP?"
    CTA_text: "The last thing you need to worry about when buying your new dream home is what to do with your old home."
    CTA_link_text: "We Can Help."
    CTA_url: https://www.hbprogram.com/why-hbp

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: "Lease Buyout Application"
    CTA_text2: "Our program can help you pay off your existing lease, so that you can buy a new home now!"
    CTA_link_text2: "Learn More"
    CTA_url2: https://www.hbprogram.com/copy-of-getting-started

third_sidebar_CTA:
  - CTA_image_path3: /img/cta-images/003.jpg
    CTA_title3: "Home Buyout Application"
    CTA_text3: "It’s simple to start the process and explore your options with the Home Buyout Program."
    CTA_link_text3: "Learn More"
    CTA_url3: https://www.hbprogram.com/copy-of-getting-started

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: true
  facebook_url: https://www.facebook.com/thefranklinteamhouston/
  linkedin_url:
  youtube_url:
  twitter_url:
  instagram_url: https://www.instagram.com/thefranklinteam/?hl=en
  pinterest_url:
  zillow_url: https://www.zillow.com/profile/TheFranklinTeam1/
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'Houston Real Estate Podcast with The Franklin Team'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Houston Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from eXp Realty - your professional Houston Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Houston, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'The Franklin Team'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Houston Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
  post_cta_image: /img/home-value.jpg
  post_cta_image2: /img/home-search.jpg

site_colors:
  brand_color: '#40667C'
  theme_color: '#000'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: black

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#40667C'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
